teorth/pfr

PFR.lean
PFR/main.lean
scripts/mk_all.sh

As a result, we move the content from `PFR.lean` to `PFR/main.lean`.

Script to import all Lean files in one `PFR.lean` file

---

PFR/entropy_basic.lean
PFR/neg_xlogx.lean

New definition of entropy, as discussed here: https://leanprover.zulipchat.com/#narrow/stream/412902-Polynomial-Freiman-Ruzsa-conjecture/topic/mathlib-only.20approach.20to.20entropy
This does not use the class ProbabilitySpace.

New entropy definition

---

PFR/ruzsa_distance.lean

Define the distance, prove two lemmas about it and state two more.
I renamed it from `dist` to `rdist`, because `dist` conflicts with a definition in mathlib.

Define the Ruzsa distance

---

PFR/ForMathlib/Jensen.lean
PFR/neg_xlogx.lean

I couldn't find the equality case of Jensen in the library, so just wrote a proof from first principles.

Equality case of jensen

---

PFR/Entropy/Measure.lean
PFR/ForMathlib/Jensen.lean
PFR/MeasureReal.lean
PFR/entropy_basic.lean
PFR/neg_xlogx.lean

Refactor the proof of `measureMutualInfo_nonneg` to treat the equality case also.

work towards `entropy_pair_eq_add`

---

PFR/FiniteMeasureFintype.lean

Some results to relate Radon-Nikodym densities w.r.t. counting measure to probability mass functions (`PMF`). These seem to indicate that it is not unreasonable to use the `pdf.isUniform`-spelling (which I view as Mathlib-canonical) for `IsUniform`, although clearly a lot of API is missing (and I'm still not sure of the best spelling).

Relating RN-density w.r.t. count to PMF to test spelling for IsUniform.

---

PFR/ruzsa_distance.lean
PFR/tau_functional.lean

Most continuity proofs (leading to the existence of tau-minimizer) are done: the main missing sorry requires continuity of products of probability measures (API that should also be developed for Mathlib).

Another try with most continuity proofs.

---

PFR/ruzsa_distance.lean
blueprint/src/chapter/distance.tex

I have made no attempt to avoid `IsProbabilityMeasure` or measurability assumptions.

Prove diff_ent_le_rdist lemmas

---

PFR/ruzsa_distance.lean

This PR deduces Lemma 3.24 as a corollary of Lemma 3.23

Comparison of Ruzsa distances, II (Lemma 3.24)

---

PFR/entropy_basic.lean
PFR/ruzsa_distance.lean
blueprint/src/chapter/distance.tex

* Also prove the result for 4 independent random variables (which was purely copy paste of the version for 3 and adding a 4th element to each list).

prove independent copies lemma

---

PFR/ForMathlib/Miscellaneous.lean
PFR/entropy_basic.lean
PFR/fibring.lean

Proves the general fibring identity
Proves a few easy prerequisites

General Fibring Identity

---

PFR/entropy_basic.lean
PFR/ruzsa_distance.lean

Proves `condDist_le'`, aka the second variant of [Lemma 3.22](https://teorth.github.io/pfr/blueprint/sect0003.html#cond-dist-fact). 
As you suggested on Zulip I've done this by also writing a few lemmas on constant random variables. One of these currently uses Fubini's theorem, which leads to an extra import; if that's a worry one can of course also prove it by converting the integrals to sums instead, but this way seemed easier for now.

Prove `condDist_le'`

---

PFR/ProbabilityMeasureProdCont.lean
PFR/ruzsa_distance.lean

Complete proof of Proposition 6.5 (tau has minimum), by filling in the remaining continuity proofs.
(Sorry about the detours, but many of the intermediate lemmas should be in Mathlib in their natural generality.)

Complete the proof of Proposition 6.5 (tau has minimum).

---

PFR/ForMathlib/Independence.lean
PFR/ForMathlib/Miscellaneous.lean
PFR/entropy_basic.lean
PFR/fibring.lean
PFR/ruzsa_distance.lean

Proves the Specific Fibring Lemma, with assorted prerequisites

Specific Fibring Lemma

---

PFR/first_estimate.lean

prove `first_estimate`

---

PFR/first_estimate.lean

Filled in the proof of `ent_ofsum_le` modulo `sum_sum_indep_of_iIndep`.
Co-authored by: @MantasBaksys

Quadruple sums modulo sum_sum_indep_of_iIndep.

---

PFR/first_estimate.lean

I filled in the small piece left from yesterday that completes the proof of `ent_ofsum_le` modulo prerequisites as in the dependency graph.

Quadruple sums.

---

PFR/endgame.lean
PFR/first_estimate.lean
PFR/second_estimate.lean
PFR/tau_functional.lean

Just add docstrings or inherit_docs to local notations, so that the meaning of the notation can be inspected by hovering.

Add docstrings or inherit_docs to local notations.

---

README.md

I'm assuming that this is a cut and paste error?

remove reference to sphere eversion

---

PFR/endgame.lean

Proves `construct_good`, assuming measurability of the `T_i`s.

prove `construct_good`

---

PFR/ForMathlib/Miscellaneous.lean
PFR/endgame.lean
PFR/f2_vec.lean
PFR/ruzsa_distance.lean
blueprint/src/chapter/distance.tex

* also fix typo in the LaTeX file
* also reformulate `ent_bsg` a bit

prove construct_good_prelim

---

PFR/first_estimate.lean

Just trying to make the proof of `ent_ofsum_le` more readable with `calc` blocks, spelling out intermediate inequalities, and arranging in clearer structure.

Clean up the proof of ent_ofsum_le.

---

PFR/Entropy/Basic.lean
PFR/Entropy/Disintegration.lean
PFR/Entropy/Kernel.lean
PFR/Entropy/KernelMutualInformation.lean
PFR/Entropy/KernelRuzsa.lean
PFR/Entropy/Measure.lean
PFR/Entropy/MeasureCompProd.lean
PFR/ForMathlib/CompactProb.lean
PFR/ForMathlib/FiniteMeasureComponent.lean
PFR/ForMathlib/Finiteness.lean
PFR/ForMathlib/MeasureReal.lean
PFR/Mathlib/MeasureTheory/MeasurableSpace/Defs.lean
PFR/ProbabilityMeasureProdCont.lean
PFR/endgame.lean
PFR/entropy_pfr.lean
PFR/f2_vec.lean
PFR/first_estimate.lean
PFR/ruzsa_distance.lean
PFR/tau_functional.lean
Test/entropy_basic_old.lean
Test/neg_xlogx_old.lean
Test/probability_space_old.lean
Test/probability_space_old2.lean
Test/set_coerce.lean
Test/test.lean

style cleanup

---

PFR/Mathlib/Data/Finset/Sigma.lean
PFR/Mathlib/Data/Fintype/Sigma.lean
PFR/Mathlib/Data/Set/Sigma.lean
PFR/Mathlib/Probability/Independence/Basic.lean

This is by copying and golfing Terence Tao's formalization of `iIndepFun.prod`.
A few lemmas are added for `Set.Sigma` and `Finset.sigma`.

feat: generalize `iIndep_fun.pi` to infinite `ι`

---

blueprint/src/chapter/distance.tex
blueprint/src/chapter/fibring.tex
blueprint/src/chapter/weakpfr.tex

Add to the blueprint all lemmas and proofs for deducing weak PFR over the integers from PFR over F_2^n.

Weak integer PFR

---

PFR/WeakPFR.lean

I also renamed the current `app_ent_PFR` to `app_ent_PFR'` and added the old `app_ent_PFR`, implemented in terms of `MeasureSpace.mk` and `app_ent_PFR'`.

feat: `PFR_projection`

---

PFR/WeakPFR.lean

I made an extremely minor mathematical simplification, replacing `2 ^ (1 - k)` by a non-negative `α`. Also, I reordered some steps for readability.

chore: `PFR_projection` cleanup

---

PFR/WeakPFR.lean
blueprint/src/chapter/weak_pfr.tex

Nothing deep here, just being a little less wasteful in the proof of Lemma pfr-projection. This makes the proof just a little bit longer (and possibly a little bit harder to read, although the idea is the same), so it's not completely obvious if this should be merged or not.

in weak_PFR, improve 40 to 34

---

PFR/Mathlib/Probability/Independence/Basic.lean

Remove says to avoid CI failure.

Remove `says`

---

PFR/MoreRuzsaDist.lean

Fixed docstrings so that they're displayed correctly in the documentation website.

Fix docstrings

---

PFR/Endgame.lean
PFR/Fibring.lean
PFR/FirstEstimate.lean
PFR/ForMathlib/Entropy/RuzsaDist.lean
PFR/ImprovedPFR.lean
PFR/WeakPFR.lean

This PR golf a few proofs using dot notation and fix a few docstrings.

Simplify proofs & fix docstrings

---

PFR/ForMathlib/Entropy/RuzsaDist.lean
PFR/MoreRuzsaDist.lean
blueprint/src/chapter/torsion.tex

Proof of `ent_of_sub_smul_le`

---

PFR/MoreRuzsaDist.lean
PFR/WeakPFR.lean

This PR proves `condMutual_comp_comp_le`, (up to adding the extra assumption that `Z` has finite range)

Prove `condMutual_comp_comp_le`

---

PFR/kullback.lean

Enhance readability in docstrings for hovering

Unicode docstrings

---

PFR/Kullback.lean
PFR/Mathlib/Probability/ConditionalProbability.lean
PFR/Mathlib/Probability/Independence/FourVariables.lean
PFR/Mathlib/Probability/Independence/ThreeVariables.lean
PFR/RhoFunctional.lean
blueprint/src/chapter/further_improvement.tex

End of the prerequisites for the rho functional (except for the continuity)

More lemmas on the rho functional

---

PFR.lean
PFR/Examples.lean

Make sure the examples are built by including them in the `PFR` folder

Move examples

---

PFR/Mathlib/Probability/Kernel/Composition/Comp.lean

These lemmas are now available in mathlib

Delete upstreamed lemmas

---

PFR/Endgame.lean
PFR/Examples.lean
PFR/ImprovedPFR.lean
PFR/Kullback.lean
PFR/Mathlib/Probability/Independence/Basic.lean
PFR/Mathlib/Probability/UniformOn.lean
PFR/MultiTauFunctional.lean
PFR/RhoFunctional.lean
PFR/WeakPFR.lean

Probably not perfect, but it builds, with a lot of `.toReal` removed.
One pain point: `ℙ.real` doesn't work, one needs to use `Measure.real ℙ`.

complete bump

---

PFR/Endgame.lean
PFR/Mathlib/Probability/IdentDistrib.lean
PFR/Mathlib/Probability/Independence/Basic.lean

I upstreamed these two lemmas to Mathlib.

chore: delete upstreamed lemmas

---

scripts/upstreaming_dashboard.py

Should fix the current CI failure.

sync `upstreaming_dashboard.py` with LeanCamCombi
