teorth/pfr

blueprint/src/web.tex, docs/_config.yml, docs/_includes/mathjax.html, docs/_layouts/default.html, docs/index.md
Various fixes have been done to make the website look nice.
- There were some capitalisation issues which made the CSS file not load (it was looking in `PFR` not `pfr`).
- MathJax wasn't supported, so I added some code to enable it.
- MathJax expects double `$$` signs to surround math mode content instead of single `$` signs.
Note: because of the interaction between Markdown and MathJax, vertical pipe symbols `|` can't be used directly, because Markdown thinks you're starting a table.
I converted each `|` into `\vert` to fix this issue.
=> Fix webpage

PFR/MeasureReal.lean, PFR/entropy_basic.lean
Given a measure `μ`, we define a function `μ.real` such that `μ.real s` is the measure of `s` interpreted as a real number instead of an extended real number. The idea is to use it everywhere to get rid off the coercions from extended real numbers, but the PR only implements the basic API and does not connect it with the other files yet. Discussion on Zulip around https://leanprover.zulipchat.com/#narrow/stream/412902-Polynomial-Freiman-Ruzsa-conjecture/topic/comments.20on.20FiniteMeasure.20user-friendliness/near/402445458
=> feat: API to interpret measures as real-valued functions

PFR/ForMathlib/Finiteness.lean, PFR/ForMathlib/Finiteness/Attr.lean, PFR/ForMathlib/Positivity.lean, PFR/MeasureReal.lean, PFR/entropy_basic.lean
This implements a prototype `finiteness` tactic, designed to solve goals of the form `*** < ∞` and
(equivalently) `*** ≠ ∞` in `ENNReal`.  There will be a lot of rough edges, it's not tested much.
See previous Zulip discussions, e.g.
https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/infinity.20in.20positivity.3F
https://leanprover.zulipchat.com/#narrow/stream/412902-Polynomial-Freiman-Ruzsa-conjecture/topic/comments.20on.20FiniteMeasure.20user-friendliness/near/402458215
=> Prototype "finiteness" tactic

PFR/FiniteMeasureFintype.lean, PFR/ForMathlib/FiniteMeasureComponent.lean, PFR/neg_xlogx.lean
Adds two files
* `PFR/ForMathlib/FiniteMeasureComponent.lean`: Shows that the measure of a connected component depends continuously on `FiniteMeasure` (in its topology of weak convergence).
* `PFR/FiniteMeasureFintype.lean`: For results on finite measures on a finite type. Contains in particular the continuous dependence of `measureEntropy` on `ProbabilityMeasure` (in its topology of weak convergence).
Also add lemma `continuous_negIdMulLog` to file `neg_x_log_x.lean`.
=> Continuity of entropy (and of point probabilities).

PFR/FiniteMeasureFintype.lean, PFR/ForMathlib/CompactProb.lean, PFR/ForMathlib/FiniteMeasureComponent.lean
This PR contains
* small improvements to the previous PR on continuity of entropy and filling in the last sorry in `CompactProba.lean` which was morally done in the previous PR;
* 1-line constructions of discrete uniform `ProbabilityMeasure`s and finite counting measures
* unconclusive / unsuccessful attempts at a good spelling of `IsUniform` with `PDF.uniformOfFinset` (these should probably be discarded once a good spelling is agreed on).
=> Small fixes + experiments on spelling IsUniform

PFR/MeasureReal.lean, PFR/entropy_basic.lean, PFR/ruzsa_distance.lean, blueprint/src/chapter/entropy.tex
I include an adjustment of the blueprint to account for a reversed dependence:  I prove this from the characterization of when mutual information is zero, rather than vice versa.  Might be worth double-checking my blueprint additions since I didn't have a way of checking the build locally.
I added assumptions `(hX : Measurable X) (hY : Measurable Y) [IsProbabilityMeasure μ]`.  Expected?
=> Entropy additive iff independent

PFR/tau_functional.lean
Continuity of tau is the essential remaining sorry in existence of tau-minimizers. I added the statement of this continuity. It needs to be reduced to the continuity of the Ruzsa distance etc., which seems to necessitate versions of those stated in terms on measures.
=> Proof structure for tau_min_exists_measure.

PFR/ruzsa_distance.lean, PFR/tau_functional.lean
The remaining thing for existence of tau minimizer is continuity statements, which should be gradually reduced to the continuity of entropy. Here a reduction of continuity of tau to the continuity of Rusza distance is added (maybe some measurability assumptions need to be added later, but I hope I did not otherwise reduce it to something unprovable).
=> Mostly reduced continuity proof of tau to that of d.

PFR/entropy_basic.lean, PFR/ruzsa_distance.lean
There is a mismatch between the hypotheses used here and what is written in the blueprint https://teorth.github.io/pfr/blueprint/sect0003.html#ruzsa-triangle-improved
I have (X, Y) independent of Z
The blueprint has (X, Z) independent of Y
Did I prove the wrong thing, or is there a typo in the blueprint?
My proof follows the proof in the blueprint (see h1, h2, etc.)
=> Prove `ent_of_diff_le`

PFR.lean, PFR/ForMathlib/Independence.lean, PFR/entropy_basic.lean, PFR/f2_vec.lean, PFR/ruzsa_distance.lean, blueprint/src/chapter/distance.tex
* There are some preliminary lemmas about independent variables in `ForMathlib/Independence`. Maybe these lemmas already exist, but I couldn't find them
* It was incredibly painful to instantiate lemma `independent_copies'` to the case with 3 explicit random variables. I did this only if the variables have the same codomain, otherwise it would be even more painful.
* I only proved `condDist_diff_le` for `Ω` and `Ω'` in the same universe level. We could remove this constraint, but I don't think it will cause many problems (except that we maybe have to write some universe levels explicitly)
* For `condDist_diff_le'` I needed `H[Y + Z; μ'] = H[Y - Z; μ']`, so I assumed `ElementaryAddCommGroup G 2`. We should probably mention in the blueprint that this lemma only holds for elementary …
=> feat: finish part 1 of Lemma 3.23

PFR/entropy_basic.lean, PFR/ruzsa_distance.lean
Proves `condDist_le`, aka the first variant of [Lemma 3.22](https://teorth.github.io/pfr/blueprint/sect0003.html#cond-dist-fact). I haven't tackled the second variant yet, but might try so tomorrow.
I've also had to introduce lemmas relating `IdentDistrib ⟨X,Y⟩ ⟨X',Y'⟩` to `IdentDistrib X X'` and `IdentDistrib Y Y'`; they currently sit just above `condDist_le`, but should probably be moved somewhere else.
=> prove `condDist_le`

PFR/HundredPercent.lean, PFR/entropy_basic.lean, PFR/ruzsa_distance.lean
In the end I have not completely followed the blueprint, as it seemed faster to formalize directly that X was uniform on a translate of `symmGroup X`: this avoids constructing another probability space later on, as `U` is simply `X - c` for any `c` which is reached with positive probability.
=> complete hundred percent

PFR/entropy_basic.lean, PFR/ruzsa_distance.lean, blueprint/src/chapter/distance.tex
Also clean up some other lemma statements
=> Finish Lemma 3.23

PFR/Entropy/Disintegration.lean, PFR/Entropy/Measure.lean, PFR/entropy_basic.lean, PFR/ruzsa_distance.lean
* Remove a few unused assumptions in already proven lemmas
* Give notation the documentation of what it's defining (i.e. mousing over `H[` will now show the documentation for `entropy`)
=> Lint some files

PFR/entropy_pfr.lean, blueprint/src/chapter/pfr-entropy.tex
As expected, the proof is just collecting a number of previously established inequalities.
It did uncover a minor typo in the paper: on page 5, in the proof of theorem 1.2, $|d[X_1; U_H ] − d[X_2; U_H ]| \le d[X_1; X_2]$ should read $|d[X^0_1; U_H ] − d[X^0_2; U_H ]| \le d[X^0_1; X^0_2]$.
=> Prove entropic_PFR_conjecture

PFR/Entropy/Measure.lean, PFR/ForMathlib/Miscellaneous.lean, PFR/HundredPercent.lean, PFR/entropy_basic.lean, PFR/entropy_pfr.lean, PFR/main.lean, PFR/neg_xlogx.lean, Test/entropy_basic_old.lean
We add more facts on uniform distributions, and the fact that the entropy of a random variable supported on a set `A` is at most `log A`. 
Also rename `isUniform` to `IsUniform` to match mathlib naming conventions.
=> prerequisites on entropy and uniform distributions for the final argument

PFR/ForMathlib/CompactProb.lean, PFR/ForMathlib/FiniteMeasureComponent.lean, PFR/ForMathlib/FiniteMeasureProd.lean, PFR/ForMathlib/ProbabilityMeasureProdCont.lean, PFR/ProbabilityMeasureProdCont.lean, PFR/ruzsa_distance.lean
I added a version of the continuity of products of probability measures on finite spaces, which should be sufficient for the remaining continuity proofs. (In Mathlib the continuity of products of probability measures should be proven for all separable metrizable spaces, but this requires a bit more.)
=> Products of probability measures.

PFR/entropy_basic.lean, PFR/entropy_pfr.lean
This PR makes a couple of modifications to `entropy_pfr` in order to get rid of the last sorries in `entropic_PFR_conjecture'`. 
I also ended up breaking up a few long lines in the files I was looking at (all the changes in `entropy_basic` are of this form) in order to make the code a bit more readable (I initially hadn't planned on doing this so I'm happy to revert these changes/do them in another PR if necessary)
=> Remove `sorries` from `entropy_pfr` 

PFR/first_estimate.lean, blueprint/src/chapter/pfr-entropy.tex
Another easy one.
I did change `h_indep` to match `sum_of_rdist_eq_char_2`. I hope this doesn't come back to bite, but for now it saves having to permute a vector.
=> Fibring identity for first estimate

PFR/Entropy/Basic.lean, PFR/endgame.lean, PFR/ruzsa_distance.lean, PFR/second_estimate.lean
Generalises `independent_copies3_nondep` and the lemmas depending on it to work with measure spaces from different universes, like the rest of the project already does.
This is not really mathematically meaningful of course and comes at the cost of making the proof of `independent_copies3_nondep` even longer, but since it's one of afaik only two lemmas still having this restriction (the other being `independent_copies4_nondep`) I thought I'd make a PR for it nonetheless.
=> remove universe constraints froms `independent_copies3_nondep`

.github/workflows/push.yml, README.md, blueprint/requirements.txt, blueprint/tasks.py, tasks.py
Per discussions with @kbuzzard and @YaelDillies , this PR includes some improvements on blueprint, namely:
1. Currently, the Mathlib doc caching is not effective, this is because the doc is moved during CI for publishing to Pages.
Fixing this should make CI faster. More deps of Mathlib are also cached.
2. `inv serve` is silent about which port it's serving, unlike `inv serve` in other repos, which would show a link to click on for convenience and less confusion.
3. Currently, after each edit to LaTeX, one must rerun both `inv all` and `inv serve`, unlike `inv dev` available in other repos, which will rebuild the blueprint on file changes, making local testing more convenient.
4. The CI uses `requirements.txt` but instructions for local testing is not using it, and it's more complicated …
=> Misc improvements on blueprint

tasks.py
This PR implements a new task `inv check` which can be run in CI or locally to check for broken references in blueprint to Lean declarations as discussed on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/412902-Polynomial-Freiman-Ruzsa-conjecture/topic/blueprint.20docs.20404).
Non-ideal side of this `inv check`:
1. It's not an ideal design, as it's implemented on the user side in formalization projects but not in `leanblueprint` itself. But this is a common issue of the blueprint ecosystem, namely every project is using a slightly different setup with a few loosely coupled building blocks, in Python, in Github Actions workflows, in LaTeX etc. Moving them into `leanblueprint` is something up to discussion but at least for me, keeping multiple projects running OK and fixing …
=> Check for broken references in blueprint to Lean declarations

PFR/f2_vec.lean, PFR/first_estimate.lean
Remove the ad hoc lemma `sub_eq_add_rv` by providing an instance of `ElementaryAddCommGroup` for random variables with values in one.
This approach is longer, but it seems more principled, and probably more generally useful. (I also added a couple of first lemmas about general characteristic `ElementaryAddCommGroup`s along the way, although the proofs are not very pretty.)
=> Remove the ad hoc lemma sub_eq_add_rv

PFR/Entropy/Basic.lean, PFR/Entropy/Measure.lean, PFR/ForMathlib/Miscellaneous.lean, PFR/main.lean
cc @sgouezel for replaced lemma `prod_finset_eq_prod` / `sum_finset_eq_sum` with mathlib4 `sum_subset` (but can be kept if desired)
=> refactor: replace ad-hoc sum lemmas with mathlib4 `Finset_sum*`

PFR/endgame.lean, PFR/f2_vec.lean, PFR/fibring.lean, PFR/main.lean, PFR/ruzsa_distance.lean, PFR/second_estimate.lean
* Use the `ElementaryAddCommGroup` instance on functions to simplify some proofs. In particular, `pi.sub_eq_add` is now just `sub_eq_add`.
* In the corollary `PFR_conjecture'`, remove the hypotheses that `G` must be equipped with a sigma-algebra, since that is not used in the statement of the theorem.
=> some cleanup

PFR/main.lean
This PR ensures that `PFR_conjecture` and `PFR_conjecture_aux` already don't have the `MeasurableSpace G` argument.
=> remove measurable space condition earlier

PFR/Entropy/Disintegration.lean
Most of the results in the Disintegration file should be changed to reuse Mathlib results about the kernels `Measure.condKernel` and `condDistrib`. See for example the new lemma `condEntropyKernel_eq_condDistrib`, which states that the new `condEntropyKernel X Y μ` introduced in this file is the same as `condDistrib X Y μ` (almost surely with respect to the law of `Y`).
=> Add a TODO about disintegration of kernels

PFR/ruzsa_distance.lean
This lemma is true (with the same proof) for any `π : G × G →+ G'` but was written only for the particular case `G' = G × G`.
=> Generalize cond_rdist_of_inj_map

blueprint/src/chapter/homomorphism.tex
`inv check`reports:
```
[WARN] The following Lean declarations are referenced in the blueprint but not in Lean:
hahn-banach
homomorphism-pfr
```
Both are simply dash issues.
Context: [Zulip 🧵 ](https://leanprover.zulipchat.com/#narrow/stream/412902-Polynomial-Freiman-Ruzsa-conjecture/topic/blueprint.20docs.20404)
=> Fix blueprint references

.github/workflows/push.yml
As reported by @YaelDillies, searching Mathlib defs/lemmas is not working on the PFR docs:
while the doc actually exists: https://teorth.github.io/pfr/docs/Mathlib/Algebra/Group/Basic.html#sub_add_comm 
The cause:
Mathlib doc is included in the generated docs (from cache), but the cache stops doc-gen4 from regenerating the Mathlib docs and declarations (which are not cached at all due to me), causing all Mathlib declarations to not be included in the final website, so people can only search PFR defs/lemmas.
This PR fixes the issue by:
- Adding `.lake/build/doc/declarations` to cache, which should include all declaration for the search function to work
- Invalidating the current incomplete cache, by changing the cache prefix
The expected result:
1. Merging this PR into master would be a …
=> Fix Mathlib search

PFR/ForMathlib/Elementary.lean, PFR/Homomorphism.lean, PFR/Mathlib/Algebra/Module/Submodule/Map.lean, PFR/Mathlib/LinearAlgebra/Basis/VectorSpace.lean
The following are staged for mathlib:
```lean
AddSubmonoid.coe_toSubmodule [Module (ZMod (n + 1)) M]
AddMonoidHom.coe_toLinearMap [Module (ZMod (n + 1)) M]
AddSubGroup.coe_toSubmodule [Module (ZMod n) G]
AddMonoidHom.coe_toLinearMapGroup [Module (ZMod n) G]
LinearMap.submoduleMap_surjective
Submodule.equivProdSubmodule
```
Note the additions to Elementary.lean are stronger than necessary, otherwise everything else is golf. In particular `hahn_banach` and `goursat` are simplified by `LinearMap.exists_extend` and `LinearMap.equivProdOfSurjectiveOfIsComp` respectively.
=> refactor(homomorphism): upstream logic to LinearAlgebra

PFR/Homomorphism.lean, PFR/Mathlib/Algebra/Module/Submodule/Map.lean, PFR/Mathlib/LinearAlgebra/Basis/VectorSpace.lean
mostly:
- ungolfing simp -> rw -> show/exact
- adding explicit types annotations and constructors wherever there's a simple way to do so
=> perf(homomorphism): save ~10 seconds or so

PFR/Mathlib/Probability/Independence/Basic.lean
This trades a `Nonempty` assumption for a `Fintype ι` assumption. Is this OK? i.e. if we need independence of an infinite family of finite sets of independent random variables, we might not be able to use `iIndepFun.pi'` (as is currently).
I'm not familiar enough with math to know if the `Fintype ι` assumption is necessary to prove `iIndepFun.pi` in "real life"; I can only intuitively justify the `Fintype (κ i)` since the relevant preimages are intersections of only `Finset`s of `ι` but all of `κ i`.
in our current `iIndepFun.pi` formalization, `Fintype ι` is used to apply `iIndepFun_iff_pi_map_eq_map`.
Maybe the optimal end state involves adapting (instead of deleting) Terence's `iIndepFun.prod` argument to generalize `iIndepFun.pi` to infinite `ι`. I'm currently trying this.
=> refactor!: prove `iIndepFun.prod` in terms of `iIndepFun.pi'`

.github/workflows/push.yml, blueprint/requirements.txt
This PR improves CI to build both PDF and web in [texlive-action](https://github.com/xu-cheng/texlive-action), reduces CI by ~5 minutes:
=> Build both PDF and web in texlive-action

PFR/Mathlib/Data/Fintype/Lattice.lean, PFR/Mathlib/Data/Fintype/Sigma.lean, PFR/Mathlib/Probability/Independence/Basic.lean
There's a bunch of golf but the relevant change is at `PFR/Mathlib/Probability/Independence/Basic.lean:319`
=> refactor: remove ad-hoc j <-> (i, j) bijection from mathlib

PFR/WeakPFR.lean
I've added the second definition of dimension given in the blueprint plus a bit of API (some of it as `proof_wanted`). Most of this should be relatively easy to prove so I'll work on that next!
=> feat: add second definition of dimension and API

PFR/Fibring.lean, PFR/ForMathlib/Entropy/RuzsaDist.lean
Proves `rdist_of_hom_le` modulo a lemma that the conditional Ruzsa distance is nonnegative. 
The blueprint proof for this statement is quite different to the proof here. Showing that X and Y are independent is not necessary and there is no other Lemma ?? needed to complete the proof.
=> Prove rdist_of_hom_le

blueprint/src/chapter/approx_hom_pfr.tex, blueprint/src/chapter/hom_pfr.tex, blueprint/src/chapter/improved_exponent.tex, blueprint/src/chapter/pfr.tex
Correct a mistake in my previous PR: I thought that in `\uses{...}`, I should mention the Lean names, while it should be the latex label. This results in a disconnected graph in the blueprint. It should be better with the current PR.
=> fix blueprint

blueprint/.gitignore, blueprint/src/chapter/distance.tex, blueprint/src/chapter/entropy_pfr.tex, blueprint/src/chapter/fibring.tex, blueprint/src/chapter/hom_pfr.tex, blueprint/src/chapter/improved_exponent.tex, blueprint/src/preamble/print.tex
I've adapted the latex template to warn when in `uses` there is something which is not a latex label. And fixed the warnings.
=> fix wrong `uses` in the blueprint

blueprint/src/chapter/improved_exponent.tex
This makes the blueprint graph connected again...
=> add empty line to workaround blueprint bug

PFR/ForMathlib/FiniteRange.lean, PFR/Mathlib/GroupTheory/Torsion.lean, PFR/WeakPFR.lean
Currently depends on `[FiniteRange X]` and `[FiniteRange Y]` due to a number of other lemmas which depend on it. This should be OK because the final `WeakPFR` result is defined over `{A : Set G} [Finite A]`.
=> feat: `torsion_free_doubling`

.github/workflows/push.yml
I've pinned the Docker image used for blueprint generation, as well as setting the `PIP_BREAK_SYSTEM_PACKAGES` environment variable to `1`. Either solution is enough to get a green build, but I think pinning the Docker image will make CI more robust in the future.
=> chore: fix blueprint generation

blueprint/requirements.txt, docs/index.md
This is needed because the blueprint plugin was split into three pieces.
=> Update blueprint installation procedure

blueprint/src/chapter/weak_pfr.tex
The proof is still fine, since the statement has the sign going the correct way.
=> chore: fix flipped sign in single_fibres blueprint

.github/workflows/push.yml
This fixes some broken Blueprint links and broken docs search entries.
=> build: un-cache PFR declarations from docs

PFR/ForMathlib/Entropy/RuzsaSetDist.lean, PFR/ForMathlib/Uniform.lean, PFR/Mathlib/Probability/Independence/Basic.lean, PFR/Mathlib/Probability/Independence/Kernel.lean, PFR/WeakPFR.lean
I add the hypotheses:
`(hUA_mem : ∀ ω, UA ω ∈ A) (hUB_mem : ∀ ω, UB ω ∈ B)`
which are returned from `exists_isUniform`.
=> feat: `single_fibres`

PFR/WeakPFR.lean, blueprint/src/chapter/weak_pfr.tex
This is a trivial improvement, using the collective bound $d[U_H, X] + d[U_H, Y] \le 10 d[X, Y]$ instead of the individual bounds $d[U_H, X] \le 11/2 d[X,Y]$ and $d[U_H, Y] \le 11/2 d[X,Y]$, as everything comes by pairs.
=> improve constant 44 to 40 in weak_PFR

.github/workflows/push.yml, PFR/ApproxHomPFR.lean, PFR/ForMathlib/Entropy/Basic.lean, PFR/ForMathlib/Entropy/Group.lean, PFR/ForMathlib/Entropy/RuzsaDist.lean, PFR/ForMathlib/Entropy/RuzsaSetDist.lean, PFR/ForMathlib/Graph.lean, PFR/ForMathlib/Uniform.lean, PFR/HomPFR.lean, PFR/ImprovedPFR.lean, PFR/Main.lean, PFR/Mathlib/Probability/Independence/Basic.lean, PFR/Mathlib/Probability/Independence/Kernel.lean, PFR/WeakPFR.lean, blueprint/src/chapter/approx_hom_pfr.tex, blueprint/src/chapter/distance.tex, blueprint/src/chapter/entropy.tex, blueprint/src/chapter/entropy_pfr.tex, blueprint/src/chapter/improved_exponent.tex, blueprint/src/chapter/jensen.tex, blueprint/src/chapter/weak_pfr.tex, examples.lean
The `Nonempty`/`Set.Nonempty` confusion was probably resolved suboptimally, but the PR builds. It targets the `bump` branch and not `master` because it built on previous work, so merging this will update #171.
=> chore: Update bump to master

blueprint/src/chapter/approx_hom_pfr.tex
=> leanok `approx_hom_pfr`

PFR.lean
The project didn't build because there was a no-longer-existing file imported.
=> lil bug fix

PFR/MoreRuzsaDist.lean, blueprint/src/chapter/torsion.tex
We had to add the following hypotheses:
- `Measurable Y`
- `Measurable f`
- `FiniteRange Y`
Co-authored-by: Lorenzo Luccioli <lorenzoluccioli@gmail.com>
=> Proof of `mutual_comp_le` & fix blueprint typo

PFR/MoreRuzsaDist.lean, blueprint/src/chapter/torsion.tex
We had to add the following hypotheses:
- `Measurable f`
- `Measurable g`
Depends on #189.
Co-Authored-By: Pietro Monticone <38562595+pitmonticone@users.noreply.github.com>
=> Proof of `mutual_comp_comp_le`

PFR/MoreRuzsaDist.lean
Remove unnecessary hypotheses `Measurable f` from `mutual_comp_le` and `mutual_comp_comp_le`.
Co-authored-by: Lorenzo Luccioli <lorenzoluccioli@gmail.com>
=> Remove unnecessary hypotheses

blueprint/src/chapter/torsion.tex
Fix `hyperref` warnings such as:
```console
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `math shift' on input line 419.
```
This warning is generated by the `hyperref` package when it encounters a math symbol in a section heading or caption, which is not allowed in a PDF string. It automatically removes the math symbol, but it still generates a warning.
Using `\texorpdfstring{$X$}{X}` prevents the warning.
=> Fix `hyperref` warning

blueprint/src/print.tex
Trivial fix substituting with `\setmainfont{latinmodern-math.otf}`.
I expect this change to make it compatible to all operating systems and models (e.g. Mac Intel, Mac M1/2/3) so that more contributors could locally compile the PDF if they need.
For more details see [here](https://github.com/ImperialCollegeLondon/FLT/issues/37) and [here](https://github.com/ImperialCollegeLondon/FLT/pull/45).
=> Fix macOS issue with latin modern math font

blueprint/src/chapter/entropy_pfr.tex, blueprint/src/chapter/improved_exponent.tex, blueprint/src/chapter/pfr.tex, blueprint/src/chapter/weak_pfr.tex
Use capitalised clever references on some remaining `Lemma~\ref`.
=> Use capitalised clever references

blueprint/src/chapter/distance.tex
We have added the lean declaration of `\lean{ent_of_diff_le}` (Improved Ruzsa triangle inequality).
=> Add missing lean declaration in blueprint

PFR/FirstEstimate.lean, PFR/ImprovedPFR.lean, PFR/MoreRuzsaDist.lean
We have fixed docstrings so that they're displayed correctly in the documentation website.
=> Fix docstrings for docs website

PFR/Mathlib/Probability/ConditionalProbability.lean, PFR/Mathlib/Probability/IdentDistrib.lean, PFR/Mathlib/Probability/Independence/Conditional.lean
=> Generalise `condIndep_copies`

blueprint/src/chapter/further_improvement.tex, blueprint/src/chapter/jensen.tex
Also added a few lemmas (for the log-sum inequality) to Chapter 1.
Some remarks: 
1. I changed the name from tau to rho to avoid confusion with the old tau
2. I didn't explicitly write down the conditional variants of the rho-inequalities because I'm not entirely sure how the lean proof works, but they should work when all the terms are further conditioned on the same random variable.
3. For Chapter 13.3 it could potentially be easier to copy the old C=11 proof, but I still wrote down the whole proof (in a slightly different way) because it seems that we need a new variant of many lemmas, and the copy-and-replace could be tricky.
=> Blueprint for C=9

PFR/RhoFunctional.lean
[LeanAgent](https://arxiv.org/abs/2410.06209) discovers a proof for a theorem with the _sorry_ keyword.
=> LeanAgent Proof

PFR.lean, PFR/ForMathlib/Entropy/Basic.lean, PFR/ForMathlib/Uniform.lean, PFR/Kullback.lean, PFR/Mathlib/Analysis/SpecialFunctions/Log/Basic.lean, PFR/Mathlib/MeasureTheory/Measure/Prod.lean, PFR/Mathlib/Probability/IdentDistrib.lean, PFR/Mathlib/Probability/UniformOn.lean, PFR/RhoFunctional.lean, blueprint/src/chapter/further_improvement.tex
We finish the file on KL divergence, and prove the first lemmas on the rho functional. I changed a little bit the implementation of rhoMinus, expressing it in terms of measures on the group to avoid universe issues (but then I proved a lemma showing that it satisfies the right inequality for random variables, whatever their universe). More importantly, I introduced an absolute continuity assumption in the definition of rhoMinus, because otherwise KLDiv is badly behaved, because we have chosen a real-valued version while the divergence should be infinite when the random variables are not absolutely continuous. 
There is a design balance here: either use the natural KLDiv, valued in [0, \infty], but then computations become a mess because you need to check all the time if the quantities are …
=> Start on the rho functional

PFR/BoundingMutual.lean, PFR/Endgame.lean, PFR/Examples.lean, PFR/Fibring.lean, PFR/FirstEstimate.lean, PFR/ForMathlib/Entropy/Group.lean, PFR/ForMathlib/Entropy/RuzsaDist.lean, PFR/ForMathlib/FiniteRange/IdentDistrib.lean, PFR/ForMathlib/FourVariables.lean, PFR/ForMathlib/ThreeVariables.lean, PFR/ImprovedPFR.lean, PFR/Mathlib/Probability/IdentDistrib.lean, PFR/Mathlib/Probability/Independence/Basic.lean, PFR/Mathlib/Probability/Independence/Kernel.lean, PFR/MoreRuzsaDist.lean, PFR/RhoFunctional.lean, PFR/SecondEstimate.lean, PFR/TorsionEndgame.lean, lake-manifest.json
In #22644, I've removed useless explicit arguments in `iIndepFun`, motivated by PFR where this was just cluttering things. In this PR for PFR, I do the corresponding cleanup.
=> bump mathlib

.github/workflows/push.yml, README.md, website/_includes/mathjax.html, website/_layouts/default.html, website/index.md
* Avoid duplication of information in `README.md` versus `website/index.md`
* the duplication above previously caused an issue that in d7157aa7c9561385b252769351b6d66af4bfac6e , some `|` was changed to `\vert` in `README.md` but the change was not correspondingly applied in `website/index.md`. With the above change, it is less likely to forget.
* also change these to `\lvert ... \rvert`. They render the same, but this seems harmless enough.
* make the link to leanblueprint clickable.
* make math formulas on the website actually render. Note that `$...$` are not converted by default unless configured.
* update CDN. https://cdn.mathjax.org is no longer functional and just redirect to cloudflare by default now.
* modify a relative URL to a path-relative URL. From my reading of the code I …
=> Fix website

CITATION.cff
Adds the last two missing real names to the authors list, those of @kkytola and me. I've also shuffled around entries to make the list alphabetically sorted by last name again.
=> chore: fill in last two real names & sort authors
